#pragma once
#include "project_config.h"

#define CONFIG_ELTARIFFS_PARAMS_LOCATION 1

#define CONFIG_ELTARIFFS_PARAMS_GROUP_KEY "eltariffs"
#define CONFIG_ELTARIFFS_PARAMS_GROUP_TOPIC "electic_tariffs"
#define CONFIG_ELTARIFFS_PARAMS_GROUP_FRIENDLY "Учёт электроэнергии"

#define CONFIG_ELTARIFFS_PARAMS_TARIFFS_KEY "t%d"
#define CONFIG_ELTARIFFS_PARAMS_TARIFFS_TOPIC "tariff%d"
#define CONFIG_ELTARIFFS_PARAMS_TARIFFS_FRIENDLY "Тариф %d"

#define CONFIG_ELTARIFFS_PARAM_TARIF_DAYS_TOPIC "days"
#define CONFIG_ELTARIFFS_PARAM_TARIF_DAYS_FRIENDLY "Дни недели"
#define CONFIG_ELTARIFFS_PARAM_TARIF_TIMESPAN_TOPIC "timespan"
#define CONFIG_ELTARIFFS_PARAM_TARIF_TIMESPAN_FRIENDLY "Интервал"
#define CONFIG_ELTARIFFS_PARAM_TARIF_PRICE_TOPIC "price"
#define CONFIG_ELTARIFFS_PARAM_TARIF_PRICE_FRIENDLY "Стоимость"

#define CONFIG_ELTARIFFS_PARAM_REPORT_DAY_TOPIC "report_day"
#define CONFIG_ELTARIFFS_PARAM_REPORT_DAY_FRIENDLY "День начала отчётного периода"